language: python
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
script:
- poetry run pytest -v
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish --build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: hQcOUTgrOJOtI2ey2ah/QPVP4PZhR/15Uqu/yVOm7SJ0Cz2RUppYS6v59pYQgspGRPxEzBQYfgLx/itvtFRc90qUR0mjJDgrkag9l6COdbcJRglrYyCFaUAnXigqdectQr64CRAREZQ4FZeNJIzqAvFGrvDxY5YqI6c8S4gQL94VH7KFCFHVxj7UV3XnIYLQVW+KnHgFMb3Yo8VRNVwfBN4R3euv5Erc/qdUNdeQ4CJ+aJg4u2AMTxNwXTA1H7mjFrTUkYc5i6j6VPldqEV8Kah3wu30aCgdEAsd5O+1kUEINjEdZjosoFHd7RGLFOqCA+oD0GkCzMJZ4qGasVGnnKykrBHz9kRV57tPJ3wr5nDmjLH5KOGrwDcBJNOlYZOGAPLSP/rhAFy7hzN0bhBPPGtV0JakfEuXr5sO5QDUBnV8LenToXeXU2srn5pZMM6IMRl/sBbw4862RvXue85JBSXXNDJuznbY/wAhl0IYew+o6v6+sFtqAdb7cVP4Vifo+XcaXQQKaZtR3+4ovVyon57DQJm1UrooNdfuvQ1ANYFCLpcfh4nUOU1hiEf75Zr8P1kRVJFPEA0+XIcr1m5mt6wExbo/snouOYBpQYeoWF/RULl2Gz5VmsJsh0raznqbiStzGf598nQ45EracMyaJfSLtUBIJ7FX5KuoXKRh/XE=
  - secure: F4JB5VApLpn//cJX1fmWTPyqWtUZN66HjKq8l+BRtTZf8IsVNk2gAWHk823fiSRFLH6+iblTN+8MVAenc0dpGIS5d1zjyp0pq6ic2Z1xGVGBG0+Gb6NjnGfdu4FALHP0DsJGj4pRspZMHmoFFCkMbdtd7YBGe92zosZeYrMbh0rqY2WeFDOLOPC912xxTHsgVFduQjTFbdq11pBF93AM1Gt0Du85lEQOwmuDbyEqVtu3/6qeG/OcTwS90ru/Qv9LOhYB+rPSLVIoyKvDq2qngjL9khZPYX03h1AJLgHQJYnplKf6q33hTvQuuoupaOm6kaJrYs+mrcQBQYZ+u2NqqJmlq0NFpKHja6d2AKFsS5JexYSlkj9ir5cFQzZYjYFHND08Ka4+I9G7slPaM6ZEx8JBBhWzcqXGvIxqeiyQk9r0LNOrSpLRAefnS5SLvj78OqKcNHamHUN1PXtLKMa6zd+EKosZJwxQlca2VXAVRHIg3rSJADQalF3JntMNMwasNnG599fqK0k4zIrzSqrSXuSQmZHznEWxjp/7rTaW5NJ0cj7kmcayXhEMu0Egi9WfaqDeM3Se/lJYc2ZbFqtEYECUBNsLDU380HquWhgI08iQ3bPExd9oDfI3EbCM7ZsvJ/+L68I2C3LQoMhD0grwIM3rRdpENVIu2nTAGwa6+dc=
