language: python
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
script:
- poetry run pytest tests/function_test.py
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish --build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: dxHce+eHRUsbK2p4IacieVKRsJK9h41EWz9wzQik5DEW/THfBW0FaTwA8ICIqVq/8xIJBYAqC15gQniT8mqFEzTcNJDBjmAgT9UfOZXoaFpV489FxNLA8p3XllkGRsTiChQeuDx4Ju3FHuGMLAbC8B5uWQk95mk6pSUjnX/mpNIWM4ZnYPCcJlhTQhoMq0LkQPlaHjD2TxTjscGGyFuZHA7LqK8Yqh5yizKvOfxbMOqi1fxyxLBYxqPuqTUPZJ4QCfU4z/Grn8qbDizJqrtO7zuc6fqGlRg+0k3BeyDK453Yp6wT226scZey6U76hSPxKiGH1W88fT1UhlZrcVzX3DeBRG3N1JyObMe0PgQbIRQHgzzRZytRj+EjyMyOobAinnYUdG+npbkt75HDVe9YxUFU8bsJ/7tuJccz6W4kho/PO5XSWWgf1xFTxkMn/yRr1vZt5ryqlyeKDwLID41DNCsgYDKI7XJoC+Y0n7TxPlS1/MaQ82HO0Qx68X1PwbbuU1jEk+pYGHtI5uGVcATrnxemJx2Ep3zCkGvZ9oaaKs4UY4+Dd74DqSNHfeBIPvZ98GBc1nGiBy0Q3QHkIxxb27u8Ee/yQYjkhtfZZ9LYctRmyi/W8Dhx/DxB6vd7lfAnSJ3T/yHRMCUeIL8d3LRu3VlJsqPm6fXGAz+OCEuKl80=
  - secure: YQKM38I+6f+Ij2Od/bMaRoRnewt0vOVzCxmPl6PWhtUbtrkMsjs7krRHYMp3jQ9qfo+xXgiziu5e+5tITEC9jrSwQY0HwvLnUFb7a5jkURFgKtzIvZYByBC2fIm1baUScm/AZK5A2clqm9Kxs1XPiLt1SoPlEGK1RY0jdNj3WjW3r3zDwK+qnLsQP36TouwwpML45Sip+Y/oW9sX9845z+Wc8AzVu+ws99PlU6BtCqiT74ATn1C1jZcvoER50lQ73T1uVqArT9x8FJRQVkoCUhNfQMbIII77iZvsdkNmQj3+f01pKo+4+57Kgo44Yc9nn1xvcDhz/W8DN7vTZhM7j+CP8vroXtCSS3k23v1X6hoIUeHnu/uQkwU17eFMe7SJAx62LgJvX8MkUUDS5h0sPkZIr/qdVcUYwcGVulQz7+/8/932EDQSDHt/xU4wxU9+lpeOWBWwx+c/yf7+csgVCh3TTkjpJse1ObBUPGuJG0wlIvt72euL/jQYgeZRJdiNaWUT5fxTS60it0Q3gWzNBj/czLyGvHWvtyL8WQdZPut9CgS5ORQbP8ahj0fRw71HS5GiaQ6wy5XiZB+YPz+dHXBWuAqaY7NBys8CU4YNxHpu8pZrqdua1kWqLoWvMVB8ll0fvX6FYo5Tartl9nMY8dNkbBBySnBwReOjM/50nMs=
