language: python
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
script:
- poetry run pytest -v
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish --build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: kQyA51Wv1092yi/3Mhyb+5hi2M+NrnU9kVxLoJh2CpleF7WNPhwaPbF3/KLWw5e2cGWnpmOG0jEorE5xa20ZFXWW04ldjQolIlYzrQWTX7ol77Ggmr7IKezESE54MVgS6JYevqqR3p47xlQZTSJPDJihx4b/SutP9WPyrC5ilNb7lNVw3G6EYXSbB7pd8pzFGNkuX5O9+eM+cTAqON9Z1u2zHZeucNSe2dyrrxb+8inbUzL7mUGXwt04A5TkZVUcXXtezjBlqgdGiUIk3l3CE57kNtecL1bCjn/hU4hqW+YYCxNiWZdsjCfDCPSS04SWnGOC0C01ctr4zna3gRnlE/WfbcIzvhOkIxTJ2Lb9932jfK917HrCAzz58Y925FJPSz6eK1wHHfFytWzOqm/83f+ZPApFBEMBeqZq101MtNz9XzmCusdDa/OpyvRNFh3cniuw6hfmxuEvV4TJeEF+aYCc5O5TXd971Q8mj+DNrG2dh1nl6tStPV9zPOyN7iVWQSD9sIDuklYmAWAevfdyQChSUXzs4a1FxZjqznSITKMKb3fuOgpn3V/ZCvW6oSkfM/BLJrWO7xvH5/5mTHCKNw+6I/tRhsq3AOd4UJRnsdisTPYoDgV7VbB/tj+RvR5WcOif2WH6Nk1e3Q7r/cMHxy9u7WXIqeuOZVdYcA9qOIE=
  - secure: RXpbVPtODUpteCk66/rT2TDkA1dXyKRtMOtpQ3F0Sj6nhhNlerFB0mtwyRTGgLaVfvC/X/oAteK+5O6ZM8FXGuQ98rv3EWvej5eRlCyNeuKhVT55FkPym1plXhm1oZB54G8QHc4QXg3fHHraYVhCpg0NtRcxKUOKWukMXdH3U946LwPH+wUsi1vwN5wtY8DGWA1x544XVjuQXrom81RIrHjy8fRgO3CZAcaRL4sdBQMRz72hkbQItXlbb5Cbs4Ov5rOUYVU07Jnh4hMDTaw2dVsfyQbZd4ENfuKlFjgRyvv+uf5mEbYmn28QjhmT1n6pO3OZhUGM9lAkomkY5aVVpfR5sFmiZZm+2OJcarg+/L0zKZ2bLl/lDPGfA77XIAdQOfdgJeR1ABIZJdw7lUIygwYtStC+XzyVRWgDJLFo9yJR0imVn1bFPLw3apEaJ/unD0ujcaO0n5lsmHx0vadEfmo88/M1h816FxmAx4I+8Ckn8Yy+xQ6dXzK1QCH53pLSGH8TQFBZTczokcsOc7BW3TpVsmFKbJv2laF5LH0lDgX1R4ZYIlbtNSELYwAtG/RUD4sj5y4vPOpB9SU/ESB2/xgT+8n1MAZTstikil9kpFHo+FJO95drkP+MdGz8CdDdR1R8bl0xgsZAqWycM0m2Ly5PDqO2km2z7ob4n48BiyA=
