language: python
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
script:
- poetry run pytest tests/function_test.py
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
env:
  global:
  - secure: p/ha/HCPZYVEuIL7w8toGY/y6RiSSKce5tQmOZSACPBrjAXDjki3NdbdiVBMWHabwDlxr/n2BczN779jInbtB19lff+tJ/+FHvC8mtjUn7kgQzPJVOaEl2DaSPMppI+tGbsYGRNa5liFtbfI2ZnqMWJVxp/f39M6pA/BL3TPYOIuzDnRKZ0ghJNkd9yxthGw3T8zHshvf+hXQozruYCS1qsBoZXPLDlf69Y1gUl+7ajwr+eyD2lqBVowG2zNErV7WmjFSXAzaYPngRvz2OyLVrTopNJ7sFdPcHYu1wBDUI3Ij7+folw/O7HSpyRaveBFQSsBXNAiVggji030/S9eOjWSeH9s8Z+XBcFnugivyRAu/pRylZahTDTBRGSVbll4zM+tseYmhOP+uHBZG4PijexYPclx35QCmZ4ubR3qHjQGzstA7lb5n9tH5Qp4vQPYop2H1yFTJT+8lPaxqKZwg3vng4PZSm9wjtptrbgq4D3pva57lXNVCeGm80lQb4THn9w8gPIlwajKKF0DrOXW6amO0Atsh4CpFoQEMQzcuHmjWcDPwjYoqFS1kazl8loAVCIfUT68rBor1tyaA3SNZihcyWzqQ9U09ZaT04Sn/Ch2hfS5yLm5ugTahpXbohAGg756fuBbjVTbW4WRosJkHclNpW86ibe7jit8/PTjAwY=
  - secure: QjiEjRz9Qpcz5+aYyQpn03zpYWcQVFemvtrixKXYx2WzSQj6ZqIwkxvvs2z1+nWpSgoka0zYKJAbyDgtTM79kpUZ2oPrTmITYRUCKZKmhLNZROAbBxbYjQg5Z9O+YaRYw+tbI+5ywS4G3Aa/9PWaFzfpIzQ6Xs7FnAa3Q9Ns8Ob1BxIs/MD+hLzjhUcU/WPTmxSX6zxOPzIUqTpHdVhitl/YF04BKIxODadap+J1YiJTEF3+CDHQZjK4PkKupMXvBNQ6JW/QNh8TYruvwehNcs4Zkl97PWh5ATmYHIcFm3A8etKchdBxa4fKF8+0bX+gVXQbYmpTyNiV9SvaA9hZIjPZVxPdy3JOCqyeA400hhsuhx/Iqkl9/l6bcAponAoSD2DmbejDWgsi0kofSkNFvU9q75EcnwkM6gWZfs47K5Oryeoq8VI6z3uASIAFrE7/2xWGPeYqIWA5pK1DyKLYTd6uwUneVwq5pSlvhTW/1S8GqLOEG2K+wUbuJYKZ1WgxhJxXKY2TZ0mEFzWEaWQunqDE+lDc7VgBwAFWnKWstf3u57mgW+9IZBqQ/ROfRJYXF09aNrEymRyhsczF3Wvxe823WKLzfenG++4LcST26kRoGkpjGGSncRfPThtLeuMGlMYGj9Td5bSPwlrizX2fdlGYAWN/mlSo9prWXS5lNcw=
