language: python
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install -v
script:
- poetry run pytest tests/function_test.py
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish --build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
 - secure: vT45AU1Zq+a9PnPxMYkvfKb3VA/oF2QjIvBRmConWdvslKdhLzuskfkoscSrny7p8BCQBFto/R1dBxivKq+hLeOZaGgGMTDmh4CzEuSA/nDP+jLWmu6I2n/V2Rr6rMYZDH1flpLwWVmY7wqIJ4zVEb6nXyy3DwNDtyQGClYuwfp7wjo4UkDDR+AbV8hqJ9zInVfQfGIyoZKt13tUX/QHgVT5IpVi2wMyt+1UPROsLsh1AIhz2KU8c+Z5wch2J4wRlmJuMwag5Z9t1U4//ryHKkOouBAMcd6RY34FB53QwE9lSPXMshoE6HZ7UbKgMClzJAeYP4uTZ1GveEer4SyCGQ/Yo7KwVdxiNzXRxD2dVrfVLsHFPoI6Sh3SqaXar4JmxWRYQcPSiG2YwIH3ydWm5++TA+0wc3kDJvdf1Iy9B5MmYfrgjWwJ+XTJqnnUcDZKEf7arvwvml57p8x/GijbRVVtRI95YBO7pPM3e0aaz8dGFGSN/tyuHmM/cSrhvaLHqVORFVl4MdqvyiAQA6rOwHB7GF2Zs8dDf5V1QVpr/kf2EQMlxXLRA5aql/10uXDjP0zVf2FO2us8NkTNRtxGjIsCrhZb0m0icMXjNhx4yRrt6UxlDTepYw4+mQfC0QW68EbIBaWhT9uQl6VgX9B6MZ8qSp9vhDDNSICdRG/ZiAQ=
 - secure: lZ8lDv/zKczHRUz+FCtYUg8pdgUMkRFNfUQRhbd5SbeHcUzyUAV0iKDYVcecZxffVsdoJGEWHHBbXFJ1sPvQfSkv60UYnFFFXzuMm2dXXmR4maKc+cbaxcL+zR3DfhkQPAdMAuaAtKrRbKbfjgpYdDJeL00YckhAKmVaw0Y1SYR/PEiIW1mHR0WM3wTtwnSU3Tdgx6VfMzaQWAVNHYemE0JWDFhEghTtHM1NQSLpVukU0G8j3+PExrwSIJ22CsViKAKDMk6E6YJVNnbgNDVifbRTg/bEaeZAlTJDAMTLAT38LfFdtUVAQQ7MVXxKExzPB6wYm5JXaHGwduUaXJpljZ0HYXNAWbbxQdUQ2lycNo5f5tcn4CcZwaZ4daXEcskZTn57Y7defZpiRrzG60tB2Z6CIamNKHsLRT8Zoa2yuzOtivZ4F/Fresqpmph7k/Ylgawd3dlWeNSrB4OVSRg6guBR8pOWBv8X7bPFikyn+kfzeG0Gw1u80iDZ/JEzpjzFkHbBTCXMGMW4SWZDsYhWpIkHCOaNBUqXR7lslASonHUUSxKORT3IW6cJlMALxk0TGPtkHBrytC+acP7QCyJXJsvfh3bQNjVvZi5YOPfLgcE7fsB6r80KHMftMuIXPDSC2UEtVMdpTZ/+XTHyuVjJ3MfW/0IuHHPma3xZf32+1oE=
